### ISSUE TITLE
Still can hear the audio when left the room

### ISSUE THREAD

**Issue by Mudrank** [benawad/dogehouse#229] opened 2021-02-15 13:58 UTC

**Comment by gsdeveloper** [comment] 2021-02-15 17:06
Duplicate of #16.

**Comment by gsdeveloper** [comment] 2021-02-15 17:13
Duplicate of #16. It's a feature and is [solved](https://github.com/benawad/dogehouse/projects/1#card-54838707)

**Comment by PixsaOJ** [comment] 2021-02-22 20:34
@benawad close this

**Closed** 2021-03-01 03:36 UTC
