### ISSUE TITLE
I can't hear voices

### ISSUE THREAD

**Issue by erfanium** [benawad/dogehouse#915] opened 2021-03-13 22:48 UTC
**Describe the bug**
When I join the rooms, I can't hear any sound

**To Reproduce**
1. Go to 'rooms'

**Expected behavior**
Hear voices

**What device are you on?**
os: Linux
browser: chrome 89.0.4389.72
Using http/https proxy

**Additional context**.
Browser console logs:
```
createWebSocket 
02:09:57.807 instrument.ts:129 new ws instance incoming
02:09:57.824 instrument.ts:129 createWebSocket 
02:09:57.824 instrument.ts:129 ws already connected
02:09:58.876 instrument.ts:129 Object
02:09:58.882 instrument.ts:129 ws opened
02:10:00.673 instrument.ts:129 join with voice server id: 
02:10:00.717 instrument.ts:129 nulling transports
02:10:00.719 instrument.ts:129 creating a device
02:10:00.735 instrument.ts:129 create recv transport
02:10:00.735 instrument.ts:129 transport options Object
02:10:04.546 instrument.ts:129 connect-transport recv success
02:10:04.588 instrument.ts:129 recv transport a24637a4-ae6f-4070-9a2f-db20046f3db7 connectionstatechange connecting
02:10:19.725 instrument.ts:129 recv transport a24637a4-ae6f-4070-9a2f-db20046f3db7 connectionstatechange disconnected
02:10:35.700 instrument.ts:129 nulling transports
02:11:12.561 instrument.ts:129 join with voice server id: 
02:11:12.589 instrument.ts:129 nulling transports
02:11:12.590 instrument.ts:129 creating a device
02:11:12.591 instrument.ts:129 create recv transport
02:11:12.591 instrument.ts:129 transport options Object
02:11:13.252 instrument.ts:129 connect-transport recv success
02:11:13.283 instrument.ts:129 recv transport 25cda82c-272a-4e47-81ce-abbb1cb3f2ef connectionstatechange connecting
02:11:28.425 instrument.ts:129 recv transport 25cda82c-272a-4e47-81ce-abbb1cb3f2ef connectionstatechange disconnected
```
There's no error in console

**Comment by benawad** [comment] 2021-03-13 22:52
Perfect!! I've been waiting for this to happen. 

Can you click on one of the people you can't hear, when the modal comes up, click on their profile picture 5 times this will print some audio debug stuff to the console and then can you paste it here

**Comment by erfanium** [comment] 2021-03-13 22:59
```
instrument.ts:129 audio-debug {currentTime: 0, paused: false, ended: false, readyState: 4, duration: Infinity, …}
02:27:25.023 instrument.ts:129 audio-debug {currentTime: 0, paused: false, ended: false, readyState: 4, duration: Infinity, …}
02:27:26.327 instrument.ts:129 audio-debug {currentTime: 0, paused: false, ended: false, readyState: 4, duration: Infinity, …}
02:27:32.829 instrument.ts:129 audio-debug {currentTime: 0, paused: false, ended: false, readyState: 4, duration: Infinity, …}
02:27:33.639 instrument.ts:129 audio-debug {currentTime: 0, paused: false, ended: false, readyState: 4, duration: Infinity, …}
.... and so on
```
‍‍‍Full object:
```
currentTime: 0
duration: Infinity
ended: false
paused: false
readyState: 4
volume: 0.5
```

**Comment by benawad** [comment] 2021-03-14 00:46
I should have read the initial log better, just looks like its disconnecting when trying to connect with `webrtc`. Could be related to your proxy.

**Comment by HasanMdArik** [comment] 2021-03-14 02:19
Browsers(most of them) don't allow media to be transferred in an HTTP connection, try using an HTTPS connection instead.

**Comment by kleo-xhindoli** [comment] 2021-03-14 09:57
This appears to be an issue for everyone now. Some people are getting this notification:
https://i.imgur.com/uiGDTjR.png

Also this message appears on every speakers profile
![image](https://user-images.githubusercontent.com/8216227/111064377-094db780-84b4-11eb-8d8a-e24a64681ae4.png)

**Comment by erfanium** [comment] 2021-03-14 10:13
@benawad I have been using this proxy for many years and I have never seen a problem. I also tried without proxy and strangely no websocket connection was made. I think somehow the service is not available in my country (Iran)

**Comment by erfanium** [comment] 2021-03-14 10:14
@MohammadArik I use https always

**Comment by navidmafi** [comment] 2021-03-16 17:27
hey i'm in iran too
the website is not loading at all without a VPN
Using Linux Mint 20
without proxy

**Comment by benawad** [comment] 2021-03-16 17:29
if you look in the network tab, what happens with the websocket connection?

**Comment by benawad** [comment] 2021-03-16 17:29
or does the `GET` request fail? Does it give a status code?

**Comment by navidmafi** [comment] 2021-03-16 17:39
![ScreenShot 2021 03 16_21 08 27](https://user-images.githubusercontent.com/46371349/111354679-d0703700-869b-11eb-94d8-eb6645b7b6a7.png)

The websocket connection fails

**Comment by navidmafi** [comment] 2021-03-16 17:42
note : website was not loading at all when i check 5 minutes ago
now the static content loading and websocket connection fails

**Comment by navidmafi** [comment] 2021-03-16 17:43
![ScreenShot 2021 03 16_21 12 50](https://user-images.githubusercontent.com/46371349/111355192-61dfa900-869c-11eb-95bf-a2d7752b838a.png)

console output

**Comment by navidmafi** [comment] 2021-03-16 17:52
again every request times out
![ScreenShot 2021 03 16_21 21 36](https://user-images.githubusercontent.com/46371349/111356479-a7e93c80-869d-11eb-911a-0b3b2eddf213.png)

**Comment by navidmafi** [comment] 2021-03-16 17:59
i will help as much as i can to solve the issue (also i have little WebRTC experience in case if its helpful)

**Comment by HasanMdArik** [comment] 2021-03-20 03:15
I think the problem is not related to webrtc or coding instead with the hosting provider's service area. I think the hosting provider of the socket's API doesn't approve the connection to Iran or any U.S. sanctioned region..

**Comment by benawad** [comment] 2021-03-20 03:17
yeah now that you mention it, google cloud might block this

**Closed as completed** 2021-03-20 13:44 UTC
Labels: bug
