### ISSUE TITLE
Chrome mobile: profile pages do not load

### ISSUE THREAD

**Issue by alexover1** [benawad/dogehouse#2815] opened 2021-05-18 05:08 UTC
**Bug**
When pressing on a user's profile on chrome on mobile, it takes over a minute to load and then does not actually load the page. 

**Video:**
https://cdn.discordapp.com/attachments/818184440714362880/844078341296488468/video0.mp4

**Comment by n3oney** [comment] 2021-05-18 10:17
This is a duplicate of #2725, all browsers on iOS are required to use the WebKit engine - even Chrome.

**Closed as completed** 2024-05-14 16:46 UTC
Labels: bug
