### ISSUE TITLE
Login issue for twitter account

### ISSUE THREAD

**Issue by nikhilpokharel44** [benawad/dogehouse#2342] opened 2021-04-26 14:50 UTC
I was trying to login via my twitter account which was authenticated before but suddenly I couldn't login and was redirected to login page again until i use my github account 
now i have completely new account opened 😌

**Comment by NatanCieplinski** [comment] 2021-04-26 15:46
Probably a duplicate of #2310

You got a new account opened because using another auth provider results in a new account. To understand why watch his [DogeLog](https://youtu.be/bngsrbFI2UY?t=240).

**Closed as completed** 2021-04-26 17:20 UTC
Labels: bug
