### ISSUE TITLE
Permit room owners to prevent explicit chat content

### ISSUE THREAD

**Issue by aaryamvn** [benawad/dogehouse#2050] opened 2021-04-16 04:14 UTC
We should be able to present room mods and owners with the ability to prevent explicit chat content in the chatbox. 

**Implementation**

Moderators will have a toggle switch when they create the room which allows them to turn the profanity filter off or on.

This preference will be stored in the DB.

On the room page, we will use the ["Bad Words Library"](https://www.npmjs.com/package/bad-words) on NPM. if the moderator/creator opted for the profanity filter.

**Comment by isaxk** [comment] 2021-04-16 06:32
I think it should be a mandatory feature

**Comment by aaryamvn** [comment] 2021-04-16 07:05
> I think it should be a mandatory feature

@isaboo i think we should turn it on by default but let mods toggle it. If they turn it off then any user that comes across their room will see a flag saying "NSFW" or something.

**Comment by TheOtterlord** [comment] 2021-04-16 09:08
Yeah, this is something I feel should be implemented soon. For now though, I've created an open-source bot, so if your rooms are getting targeted, feel free to run the bot on an alt account: https://github.com/TheOtterlord/dogemod

**Comment by aaryamvn** [comment] 2021-04-16 09:52
cool @TheOtterlord , ill work on implementing it out of the box

**Comment by TheOtterlord** [comment] 2021-04-16 13:21
Closing as duplicate of #251 to keep conversation in one place

**Closed as completed by TheOtterlord** 2021-04-16 13:21 UTC
Labels: enhancement
