### ISSUE TITLE
Kousa error on Deafen/Undeafen

### ISSUE THREAD

**Issue by nadirabbas** [benawad/dogehouse#2270] opened 2021-04-23 09:54 UTC
![image](https://user-images.githubusercontent.com/38838675/115854503-bc121d80-a443-11eb-9570-8030fd86d526.png)

**Comment by amitojsingh366** [comment] 2021-04-23 11:35
this is not an issue, it's caused by the latest version of the api not being deployed.
and the deafen feature works perfectly except the fact that no one else in the room knows that you've deafened *(which will be fixed after the api is deployed)*

**Closed as completed by amitojsingh366** 2021-04-23 11:35 UTC
Labels: bug
