### ISSUE TITLE
Dogehouse app crashes on mac whenever I try to login

### ISSUE THREAD

**Issue by ghost** [benawad/dogehouse#1438] opened 2021-03-21 15:32 UTC
![image](https://user-images.githubusercontent.com/81065901/111910748-a7c7b300-8a88-11eb-8fe0-8a50c7e5475b.png)

**Comment by goldyydev** [comment] 2021-03-21 15:33
Duplicate of #1229

**Closed as completed by goldyydev** 2021-03-21 15:33 UTC
Labels: bug
