### ISSUE TITLE
New Version Bug: Browsers without latest CSS standard have a broken UI

### ISSUE THREAD

**Issue by MrDogeBro** [benawad/dogehouse#1934] opened 2021-04-09 19:11 UTC
### Description
So I use Firefox as my daily driver browser and whenever I go to check out the new design for DogeHouse, the UI always fails to load correctly. It is all stuck up against the left side of the screen, not in the center like it should be. Plus theres other things like the icons make the text thats supposed to be next to them go to the next line (or something like that). I even tried the new design in a version of Firefox on my computer that is basically a fresh install, no extensions, themes, etc. and that still didn't work. Below I have attached screenshots of the new design in both the Brave browser and Firefox. The screenshots were both taken on the same monitor one after another. 

Also, I have cloned the repo to my own computer which is up to date from origin at the time or writing this. This still did not work and the result was the same as on `next.dogehouse.tv`. This is confusing me as to why this is happening so if you have any ideas just let me know. If you need any more information please ask as I would be happy to provide any needed information or anything like that. 

### Reproduction
Open `next.dogehouse.tv` in a Gecko browser.

### Expected Behavior
The UI should look the same on both Chromium and Gecko based browsers.

### Screenshots
**Brave Browser (Chromium Based)**
![Cap 04-09-21 15 06 37](https://user-images.githubusercontent.com/35872177/114229260-90703d00-9945-11eb-8756-79bbc007adab.png)
![Cap 04-09-21 14 35 08](https://user-images.githubusercontent.com/35872177/114227739-5e5ddb80-9943-11eb-8f1e-4e5a118e5f99.png)

**Firefox Browser (Gecko Based)**
![Cap 04-09-21 15 07 02](https://user-images.githubusercontent.com/35872177/114229269-9403c400-9945-11eb-918e-e8da8bd1b547.png)
![Cap 04-09-21 14 35 38](https://user-images.githubusercontent.com/35872177/114227786-703f7e80-9943-11eb-8ca1-030f8eb6ca2e.png)

### Device
MacPro 3,1 (64 Bit) running 10.11.6

### Additional Context
Firefox Version: 78.9.0esr (64-bit)
Brave Version: 1.21.74
Screen Resolution: 1920x1080

**Comment by ajmnz** [comment] 2021-04-09 19:38
Does updating Firefox to latest (87.0) fix the issue?

**Comment by benawad** [comment] 2021-04-09 20:14
The problem is this css is not being applied

```
html
  *:not(head *, script, style, .MuiDialog-root, .MuiDialog-root
    *, .block, .inline-block, .inline, .inline-flex, .table, .table-caption, .table-cell, .table-column, .table-column-group, .table-footer-group, .table-header-group, .table-row-group, .table-row, .flow-root, .grid, .inline-grid, .contents, .hidden, .sm\:hidden, .sm\:flex) {
  display: flex;
}
```

idk why new firefox wouldn't support it, maybe we need to just refactor off of this

**Comment by MrDogeBro** [comment] 2021-04-09 20:36
@ajmnz I am not able to update to latest Firefox (when I go to download a non ESR version of Firefox it gives me ESR anyways) but I tried on an Arch Linux vm with the latest Firefox installed (specifically 87.0-1) and it seems to be fixed in the latest non ESR build. It also seems that 78.9.0 is the latest ESR release which is kinda like an LTS from what I understand. Not all the newest features but is meant to be more stable for long term uses. 

@benawad I don't know why that wouldn't be supported in a recent version of Firefox though. I wonder if it could have something to do with some of the new features in Firefox that have not made their way into the ESR versions yet. If so, than it might need to be refactored for backwards compatibility.

Also I found [this chart](https://wiki.mozilla.org/Release_Management/Calendar) that shows all of the different Firefox releases. On the chart is basically shows 78.9 ESR release as the same release date as 87.0 and that 78.9 ESR is the latest ESR.

**Comment by BronzW** [comment] 2021-04-09 20:41
I thought firefox used chromium now? Is it problem with the not pseudo element or what?

**Comment by MrDogeBro** [comment] 2021-04-09 20:46
> I thought firefox used chromium now?

No it uses Gecko still. Mozilla developed Gecko so I don't know if they will ever move to Chromium.

**Comment by amitojsingh366** [comment] 2021-04-09 23:47
my firefox runs fine?
![firefox](https://cdn.discordapp.com/attachments/823238517412724786/830226900894351410/unknown.png)
![image](https://user-images.githubusercontent.com/35400192/114250662-1cff1780-99a7-11eb-8eae-0f965147d082.png)

**Comment by amitojsingh366** [comment] 2021-04-10 00:15
dosen't happen to me on firefox but the exact same thing does happen to me on the electron app *(which is chromium based)*
<img width="1439" alt="Screen Shot 2021-04-10 at 3 13 48 AM" src="https://user-images.githubusercontent.com/35400192/114251780-fe9b1b00-99aa-11eb-8b0f-dfc020183605.png">

**Comment by MrDogeBro** [comment] 2021-04-10 01:02
> my firefox runs fine?


Like I said, it runs fine when I use the latest standard release of Firefox but when I run the latest ESR version (the version I use on my Mac) it is broken.

But with what you said about it being broken in electron, I guess then it is not specifically a Gecko or Chromium issue but an issue with that css feature that Ben talked about not working in certain versions of both.

**Comment by TheOPtimal** [comment] 2021-04-10 07:36
ESR's main goal is to be secure and stable, not to be up to date. So it looks like the ESR version is missing some sort of web standard.

**Comment by TheOtterlord** [comment] 2021-04-10 08:07
Broken in Electron: Chromium 87

**Comment by borisgrigorov** [comment] 2021-04-10 16:33
I have the same problem in electron version.

**Comment by amitojsingh366** [comment] 2021-04-12 11:52
i fixed this problem on baklava by migrating to electron `12.0.2` which uses chromium `89.0.4389.90`. turns out the issue was that the `:not()` pseudo class in css only started accepting a list of classnames after chromium `88.x`. Should be a similar fix for your firefox aswell, bump chromium. re-open if issue still persists.

**Comment by MrDogeBro** [comment] 2021-04-12 11:58
Um.....this means only the most recent browsers could support the UI loading correctly, which is not the solution. The solution needs to be changing this line of css because on the web, backwards compatibility is everything. Like for me, I am on the latest esr release of firefox and it doesn't work, but there for sure needs to be backwards compatibility. Also, firefox runs on Gecko and not Chromium......but you need to reopen this issue because this is something that needs to be fixed.

**Comment by amitojsingh366** [comment] 2021-04-12 12:01
yes you do have a point. ill reopen this and change the name to make it more clear

**Comment by amitojsingh366** [comment] 2021-04-12 12:05
according to https://developer.mozilla.org/en-US/docs/Web/CSS/:not#specifications firefox 84+ should support the selector list, hence my firefox being 88.0b9 supports it.

**Comment by MrDogeBro** [comment] 2021-04-12 12:56
Yes, but for example, 78.9 is the latest ESR release of firefox, which is basically a version of firefox that is meant for stability and security, not necessarily the newest features, which doesn't support this, even though if you look at [this chart](https://wiki.mozilla.org/Release_Management/Calendar), 78.9 ESR was released at the same time of standard v87 (latest) release......

**Comment by benawad** [comment] 2021-04-15 16:53
@MrDogeBro I changed how we do the css, I think this should be fixed now, but plz reopen if you are still seeing it broken

**Closed as completed by benawad** 2021-04-15 16:53 UTC

**Comment by MrDogeBro** [comment] 2021-04-16 17:51
Yup that seems to be fixed now. It all looks great. Thanks for doing that!
