### ISSUE TITLE
this is a bug?

### ISSUE THREAD

**Issue by ghost** [benawad/dogehouse#611] opened 2021-03-07 04:17 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
https://media.discordapp.net/attachments/817228555258953738/817974138731233310/unknown.png

**What device are you on?**

**Additional context**
well i see the console and i see when a ws open

**Comment by ermalsh** [comment] 2021-03-07 04:24
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> https://media.discordapp.net/attachments/817228555258953738/817974138731233310/unknown.png
> 
> **What device are you on?**
> 
> **Additional context**
> well i see the console and i see when a ws open

This is fine, not a bug. Just websocket logging stuff.

**Comment by Mudrank** [comment] 2021-03-07 09:11
@nadirabbas @benawad  close this issue

**Closed as completed** 2021-03-07 09:16 UTC
Labels: bug
