### ISSUE TITLE
HTML tags

### ISSUE THREAD

**Issue by ghost** [benawad/dogehouse#2851] opened 2021-05-20 15:40 UTC
**Describe the bug**
A bug making DogeHouse crash when you add an a tag to the chat text.

**To Reproduce**
1. Send a message in chat.
2. Inspect element and add \<strong\>hi\</strong\> 
3. Delete the message

**Expected behavior**
It should delete the message without any error.

**What device are you on?**
I tried this all all devices.

**Comment by jcsrb** [comment] 2021-05-21 11:30
using "Inspect element" is probably out of scope for protecting against
what is the use-case of manually modifying the DOM?

**Comment by ghost** [comment] 2021-05-21 16:36
> using "Inspect element" is probably out of scope for protecting against
> what is the use-case of manually modifying the DOM?

Well its still bad

**Comment by willdoescode** [comment] 2021-05-21 20:26
You manually added a element that was not supposed to be there, this is not a bug with dogehouse.

**Closed as completed by willdoescode** 2021-05-21 20:26 UTC
Labels: bug

**Comment by ghost** [comment] 2021-05-22 10:02
well NVM
