### ISSUE TITLE
upload custom avatar

### ISSUE THREAD

**Issue by Mudrank** [benawad/dogehouse#614] opened 2021-03-07 09:12 UTC

**Comment by AkiraTenchi** [comment] 2021-03-07 13:53
It uses your GitHub avatar when logging in via GitHub so you could just upload a custom avatar here on GitHub.

**Comment by goldyydev** [comment] 2021-03-13 17:09
Maybe we can resolve this by patching Gravatar into dogehouse?

**Comment by goldyydev** [comment] 2021-03-20 19:45
Duplicate of #569

**Closed as completed by goldyydev** 2021-03-20 19:45 UTC
Labels: enhancement
