### ISSUE TITLE
WS reporting incorrect amount o people in room.

### ISSUE THREAD

**Issue by crispyaus** [benawad/dogehouse#1219] opened 2021-03-19 00:10 UTC
**Describe the bug**
The WebSocket and front end room counter is reporting the wrong number of people on a room.

**To Reproduce**
1. Go to https://dogehouse.tv
2. Look at any room which is mid-large.
3. Observe the listener count
4. Join the room and count how many people are in it
5. The count will be different

You can also see the bug in action on this public API: https://api.dogehouse.xyz/v1/popularRooms. Observe one of the rooms and see how the numPeopleInside field is different to the actual people in the room on dogehouse.tv. *not peoplePreviewList*

**Comment by daloes** [comment] 2021-03-19 13:46
I think this is dup of #1135

**Comment by goldyydev** [comment] 2021-03-20 20:41
Duplicate of #1135

**Closed as completed by goldyydev** 2021-03-20 20:41 UTC
Labels: bug
