### ISSUE TITLE
outline: none

### ISSUE THREAD

**Issue by dk-raw** [benawad/dogehouse#1912] opened 2021-04-09 15:04 UTC
All the links in the new UI have the outline when focused, please add ` outline: none` for all the links in the UI.
![Screenshot 2021-04-09 175937](https://user-images.githubusercontent.com/68110106/114200497-efda4700-995d-11eb-8a45-a89a503bab06.jpg)
![Screenshot 2021-04-09 175916](https://user-images.githubusercontent.com/68110106/114200503-f1a40a80-995d-11eb-8b39-266fbf9244bc.jpg)
![Screenshot 2021-04-09 180016](https://user-images.githubusercontent.com/68110106/114200518-f49efb00-995d-11eb-846b-46b7951aa2a0.jpg)
![Screenshot 2021-04-09 180043](https://user-images.githubusercontent.com/68110106/114200531-f799eb80-995d-11eb-8ad3-1cf0ddda8a05.jpg)

**Comment by TheOtterlord** [comment] 2021-04-09 15:14
Duplicate of #1369 
Please see [here](https://github.com/benawad/dogehouse/issues/1369#issuecomment-803393161) for more information

**Closed as completed by TheOtterlord** 2021-04-09 15:14 UTC
Labels: bug
