### ISSUE TITLE
Avatar of ppl not showing up in the PROFILE 

### ISSUE THREAD

**Issue by ghost** [benawad/dogehouse#1480] opened 2021-03-22 08:40 UTC
![image](https://user-images.githubusercontent.com/81065901/111962500-60890300-8b18-11eb-8e5f-48f4c0ce2565.png)

**Comment by TheOtterlord** [comment] 2021-03-22 08:44
Working for me, but I've not tested in chrome (working in app (chromium-based) and firefox)

**Comment by ghost** [comment] 2021-03-22 11:44
its the web version that has the issue

**Comment by goldyydev** [comment] 2021-03-26 20:53
This issue is caused by users being able to set their profile url to `https://avatars.githubusercontent.com/u/`

**Comment by 1kvsn** [comment] 2021-03-27 07:10
I've pushed the fix here:
https://github.com/benawad/dogehouse/pull/1623

**Comment by goldyydev** [comment] 2021-03-27 15:31
Fixed in #1626

**Closed as completed by goldyydev** 2021-03-27 15:31 UTC
Labels: bug
