### ISSUE TITLE
Add a REAL privacy policy and terms of service!

### ISSUE THREAD

**Issue by CreativeQuilt** [benawad/dogehouse#1837] opened 2021-04-05 19:28 UTC
**Is your feature request related to a problem? Please describe.**
The privacy policy is a rickroll and is required by COPPA law

**Describe the solution you'd like**
A privacy policy and terms of service page

**Comment by fishsticks89** [comment] 2021-04-06 21:31
The rickroll is a great privacy policy 🤔

**Comment by TheOtterlord** [comment] 2021-04-07 18:52
Duplicate of #1595

**Closed by TheOtterlord** 2021-04-07 18:52 UTC
Labels: enhancement
