### ISSUE TITLE
Regular auth, not just OAuth

### ISSUE THREAD

**Issue by samarmohan** [benawad/dogehouse#1436] opened 2021-03-21 15:28 UTC
**Is your feature request related to a problem? Please describe.**
Add normal authentication using normal usernames and passwords

**Describe the solution you'd like**
normal Elixir/Phoenix auth solutions

**Comment by f1shy-dev** [comment] 2021-03-21 16:16
We could, but then we would have to implement things such as profile picture filtering and things ourselves right? Oauth just is easier. I guess when we release `kibbeh` we could add Google and other commonly used providers too.

**Comment by HarrisonMayotte** [comment] 2021-03-31 03:06
Short term oauth is probably easier but it would make sense later down the line to be able to make accounts locally.

**Comment by TheOtterlord** [comment] 2021-04-22 08:21
Closing as duplicate of #842

**Closed as completed by TheOtterlord** 2021-04-22 08:21 UTC
Labels: enhancement
