### ISSUE TITLE
Audio Stops Working after few seconds of joining room 

### ISSUE THREAD

**Issue by aarsxx** [benawad/dogehouse#2402] opened 2021-04-28 04:17 UTC
Describe the bug
I tried joining a room today and after a few seconds, the audio stopped. I tried reloading the page and after a few seconds, the audio stopped. I thought it might have something to do with that room, but when I went to a different room, the same error happened.

To Reproduce

    Go to dogehouse dashboard
    Click on any room
    join and wait a few seconds
    See error

Expected behavior
What I expected it to do is play the audio for that room.

What device are you on?
MacBook Pro 13" 2018

Additional context
OS: macOS 11.4
Browser: Firefox Dev Editon

**Comment by dk-raw** [comment] 2021-04-28 13:55
I cannot reproduce the bug

**Comment by dk-raw** [comment] 2021-04-28 13:57
Duplicate of #2385

**Closed as completed by dk-raw** 2021-04-28 13:57 UTC
Labels: bug
