### ISSUE TITLE
Chat becomes misaligned when zoomed into 110% or more

### ISSUE THREAD

**Issue by okdargy** [benawad/dogehouse#1507] opened 2021-03-23 01:29 UTC
**Describe the bug**
The chatbox goes more down and is misaligned.

**To Reproduce**
1. Go to any DogeHouse room
2. Open the chat
3. Make page zoomed in 110% or more
4. See issue

**Expected behavior**
Supposed to be aligned and have the gray line connected at the top.

**Screenshots**
![image](https://user-images.githubusercontent.com/76412158/112078864-27b75100-8b4d-11eb-9848-8cb653b2c267.png)

**What device are you on?**
Chromebook

**Additional context**
This does not happen when you zoom out, only when you zoom in.

**Comment by wes337** [comment] 2021-03-23 05:46
Related to #1050, I don't think this is actually caused by zooming.

[Although we should support zooming up to 400%](https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Resize_content), this doesn't seem to cause any loss of content or functionality.

**Comment by TheOtterlord** [comment] 2021-04-16 08:15
Closed as Kofta is deprecated. If zooming is a problem in Kibbeh, please open a new issue with the new details

**Closed as completed by TheOtterlord** 2021-04-16 08:15 UTC
Labels: bug, kofta
