### ISSUE TITLE
SmartScreen warning when using Windows installer 1.0.29

### ISSUE THREAD

**Issue by cstmth** [benawad/dogehouse#1681] opened 2021-03-30 10:39 UTC
**Describe the bug**
Windows Defender invokes a SmartScreen warning when launching the .exe file provided in release 1.0.29 for the first time. It can be ignored by clicking on "More information" and "Run anyways".

**To Reproduce**
1. Download DogeHouse-Setup-1.0.29.exe from https://github.com/benawad/dogehouse/releases/tag/v1.0.29
2. Run the executable with Windows Defender enabled (default)

**Expected behavior**
SmartScreen warning should not appear

**Screenshots**
https://prnt.sc/10zubgf

**What device are you on?**
Windows 10 PC running 20H2

**Additional context**
Issue should be self explanatory

**Comment by TheOtterlord** [comment] 2021-03-30 10:41
Duplicate of #1376

**Closed as completed by TheOtterlord** 2021-03-30 10:41 UTC
Labels: bug

**Comment by cstmth** [comment] 2021-03-30 11:08
Sorry for the duplicate, the issue did not come up when just searching "SmartScreen".
