### ISSUE TITLE
No avatars in chat

### ISSUE THREAD

**Issue by recalcitrantjim** [benawad/dogehouse#1449] opened 2021-03-21 18:12 UTC
**Describe the bug**
Some avatars don't show in chat.

**To Reproduce**
1. Go to a meeting
2. Open chat
3. See error

**Expected behavior**
Avatars to appear

**Screenshots**
![Screenshot_20210321-130458.png](https://user-images.githubusercontent.com/77511422/111915965-c60cbf00-8a46-11eb-831c-f3a266568487.png)

**What device are you on?**
Android phone, chrome, Progressive web app

Edit: added context to device

**Comment by ghost** [comment] 2021-03-22 01:50
@that1ipodguy Unable to reproduce on pc / mac. Can you let me know if it is the same on the native mobile app ?

**Comment by that1ipodguy** [comment] 2021-03-22 07:21
odd I was using the Chrome Progressive web app version on mobile

**Comment by 1kvsn** [comment] 2021-03-27 09:47
There are multiple Avatar related issues active as of today, 27th Mar 2021. If the Avatar component doesn't receive a valid src, the onError is fired and we have **usernameForErrorImg** prop for this purpose. This prop was not passed in RoomChatList component. I've fixed it here:

https://github.com/benawad/dogehouse/pull/1626

**Comment by HarrisonMayotte** [comment] 2021-03-27 15:20
Merged into staging.

**Closed as completed by HarrisonMayotte** 2021-03-27 15:20 UTC
Labels: bug
