### ISSUE TITLE
Kousa: Error Notification

### ISSUE THREAD

**Issue by SalihSaygi** [benawad/dogehouse#1838] opened 2021-04-05 19:33 UTC
**Describe the bug**
Notification gives a json formatted error.

**To Reproduce**
1. Go to 'dashboard'
2. Click on 'a room that no longer exists'
4. See error as a notification.

**Expected behavior**
I expected to not see a json formatted error,
**Screenshots**
![image](https://user-images.githubusercontent.com/61725374/113617309-0bb2b580-960b-11eb-9c18-1d5104e82a82.png)

**What device are you on?**
Chrome, Desktop

**Comment by SalihSaygi** [comment] 2021-04-05 20:45
Later on when you join an actual room, you can't hear anything unless you refresh.

**Comment by akawajid** [comment] 2021-04-06 13:02
Duplicate of #1771

**Closed as completed** 2021-04-06 18:36 UTC
Labels: bug
