### ISSUE TITLE
New Version Bug: Design sticks to the left in Opera GX

### ISSUE THREAD

**Issue by ambozz** [benawad/dogehouse#1909] opened 2021-04-09 14:12 UTC
**Describe the bug**
The design Sticks to the Left in Opera GX and not to the middle like it normally should.

**To Reproduce**
Install Opera GX and open the website.

**Expected behavior**
That the Design sticks to the middle like in any other browser and how it is intended.

**Screenshots**
![Screenshot](https://i.imgur.com/GNIIdeN.png)

**What device are you on?**
Windows 10 with Opera GX obviously

**Additional context**
In the normal Opera Version it works as intended.

**Comment by Zamion101** [comment] 2021-04-09 14:53
It looks like even though the issues (#1766 and #1803) are closed, the issue still exists.

**Comment by EliTheCoder** [comment] 2021-04-09 22:00
Confirmed on Opera GX LVL2 (core: 73.0.3856.427) and Windows 10 64-bit

**Comment by BronzW** [comment] 2021-04-14 14:24
This has been fixed now!
![image](https://user-images.githubusercontent.com/50546858/114726678-e37b3300-9d3d-11eb-922e-3080fc4e1494.png)

**Closed as completed** 2021-04-14 17:37 UTC
