### ISSUE TITLE
Display issue on profil menu

### ISSUE THREAD

**Issue by Redeltaz** [benawad/dogehouse#2148] opened 2021-04-19 14:43 UTC
**Describe the bug**
When you click on the round icon of your profil (in top right) the text "report a bug" in french doesn't display very good 

**To Reproduce**
1. Click on your round icon in top right
2. Choose "french" for the langage
3. You're going to see the display problem

**Expected behavior**
The sentence should not return to the line below

**Screenshots**
![image](https://user-images.githubusercontent.com/62705636/115255004-29fdd280-a12e-11eb-91d7-f2eec494f969.png)

**What device are you on?**
Acer QG241Ybii screen, size is 23,8 "

**Comment by Redeltaz** [comment] 2021-04-19 14:45
There is the same problem for other langages

**Comment by wes337** [comment] 2021-04-19 14:57
I believe this is a duplicate of #2018 and was fixed with #2135

**Comment by etteryand0** [comment] 2021-04-19 14:58
It's ok in Russian. Maybe this issue could be used with white-space..? Some time ago I faced the same issue and found solution on stackoverflow

**Comment by benawad** [comment] 2021-04-19 15:22
should be fixed in latest deploy

**Closed as completed by benawad** 2021-04-19 15:22 UTC
Labels: bug
