### ISSUE TITLE
New Version Bug: please someone just add this my eyes are in pain

### ISSUE THREAD

**Issue by michaelcanudas** [benawad/dogehouse#1854] opened 2021-04-06 18:46 UTC
**Bug:**
YOU FORGOT TO REMOVE THE OUTLINE FOR SELECTED ITEMS

**To Reproduce:**
GO TO THE MAIN PAGE AND CLICK A BUTTON AHHHHHHHHHHHHHH

**Expected behavior:**
NO OUTLINE IT RUINS THE UI

**Screenshots:**
![image](https://user-images.githubusercontent.com/63616729/113762575-bba92100-96e6-11eb-92f5-2fc4a8fec296.png)

**What device are you on?**
PC (IM USING WEB VERSION BUT I ASSUME IT IS ON ALL VERSIONS)

**Additional context:**
PLEASE FIX MY EYES AHHHHHHHHHHHHHH

I EVEN WROTE THE CODE FOR YOU JUST ADD IT PLEASE:

 just add this to index.css

*:focus {
  outline: none;
}

**Comment by babeuh** [comment] 2021-04-06 18:54
Duplicate of #1844

This cannot be done because of the ARIA guidelines

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA

**Closed as completed** 2021-04-06 18:58 UTC
