### ISSUE TITLE
Confirm interaction popup out of alignment in FireFox 

### ISSUE THREAD

**Issue by manaskhandelwal** [benawad/dogehouse#758] opened 2021-03-12 19:19 UTC
#### **Describe the bug**
When we open a dogehouse room directly with a URL in Firefox, the popup to confirm an interaction is out of alignment.
<br />
#### **Expected behavior**
![image](https://user-images.githubusercontent.com/53651226/110987694-79b1e700-8395-11eb-9a64-0230e7855e66.png)
<br />
#### **Screenshots**
![mozBub2](https://user-images.githubusercontent.com/53651226/110987713-80405e80-8395-11eb-8ebd-924d5f93ccdc.png)
<br />
#### **What device are you on?**
Windows 10
FireFox `86.0`
<br />
#### **Additional context**
The popup is scrollable and we can see the chat and even send message
![image](https://user-images.githubusercontent.com/53651226/110988386-78cd8500-8396-11eb-84ee-01bfe395ed6e.png)
![bug123](https://user-images.githubusercontent.com/53651226/110988951-35274b00-8397-11eb-9ac5-47c56ab3c70b.png)

**Comment by ccoder1337** [comment] 2021-03-12 19:23
Can confirm this

**Comment by l3gacyb3ta** [comment] 2021-03-12 20:41
I have replicated the bug on Windows 10 Pro 20H2, Firefox 86.0.1.

**Comment by l3gacyb3ta** [comment] 2021-03-13 00:52
I have done some further investigations, and it seems that the issue is only with the Gecko rendering engine, as all the chromium-based browsers I have tested (Chrome, and Brave) do not seem to have this issue.

**Comment by TheOtterlord** [comment] 2021-04-16 08:19
Closed as Kofta is deprecated

**Closed as completed by TheOtterlord** 2021-04-16 08:19 UTC
Labels: bug, kofta
