### ISSUE TITLE
Windows Installer triggers Windows Install Warning (1.0.23)

### ISSUE THREAD

**Issue by sudocode1** [benawad/dogehouse#1574] opened 2021-03-25 15:53 UTC
**Describe the bug**
When running the installer, the "this might not be safe to run" image appears. (shown below)

**To Reproduce**
1. Go to https://github.com/benawad/dogehouse/releases/tag/v1.0.23
2. Download the installer EXE
3. Open it

**Expected behavior**
No error was expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/52894745/112502518-0d19ed80-8d82-11eb-8a2a-28e6cadcac3f.png)

**What device are you on?**
Windows 10 Pro N (10.0.19042) Build 19042

**Additional context**
Might require to add a publisher certificate(?) somehow.

**Comment by samarmohan** [comment] 2021-03-25 15:54
That was already mentioned in the docs, just click run anyway.

**Comment by goldyydev** [comment] 2021-03-25 15:55
Duplicate of #1376

**Closed as completed by goldyydev** 2021-03-25 15:55 UTC
Labels: bug
