### ISSUE TITLE
emoji to high

### ISSUE THREAD

**Issue by abdpro300** [benawad/dogehouse#1003] opened 2021-03-15 07:47 UTC
![image](https://user-images.githubusercontent.com/79415304/111119956-d3740600-857b-11eb-83f8-38df035e7a74.png)
thats it
emoji to high

**Comment by Rexogamer** [comment] 2021-03-15 07:56
Can't reproduce, can you share your device and browser info?

**Comment by edumorlom** [comment] 2021-03-15 09:38
Can't reproduce either on latest Firefox, Chrome and Safari on MacOS 11.3

**Comment by yummyweb** [comment] 2021-03-16 04:26
I also can't reproduce. Please provide proper information i.e. device information or steps to reproduce, otherwise I suggest to close this issue.

**Comment by navidmafi** [comment] 2021-03-16 17:18
Can't reproduce 

![image](https://user-images.githubusercontent.com/46371349/111351930-ea5c4a80-8698-11eb-9e72-80e7a483d4e2.png)

please provide more info

**Comment by A-Yamout** [comment] 2021-04-24 22:08
@abdpro300 Could you please tell us what browser and the version of it that you are using?

**Comment by ghost** [comment] 2021-04-24 22:15
This just seems extremely stale, considering we switched to a completely new design. I would recommend closing this.

**Closed as completed** 2021-04-29 14:00 UTC
Labels: bug
