### ISSUE TITLE
room gone error message stacks on top of each other

### ISSUE THREAD

**Issue by scandar** [benawad/dogehouse#2338] opened 2021-04-26 14:22 UTC
**Describe the bug**
clicking the back button to go to the previous page when the previous page is a room that no longer exists redirects you to the homepage again if you keep clicking back it keeps redirecting and displays the 'room gone' flash message everytime

**To Reproduce**
1. Go to a room
2. end it and you should be redirected to the home page
3. click the back button as many times as you want

**Expected behavior**
the error message should be displayed once, or display a 404 page instead.

**Screenshots**
![image](https://user-images.githubusercontent.com/25529286/116098082-106b0680-a6ab-11eb-920f-0d38111fecf2.png)

**Comment by NatanCieplinski** [comment] 2021-04-26 15:37
Probably a duplicate of #2157

**Closed as completed** 2021-04-29 19:25 UTC
Labels: bug
