### ISSUE TITLE
Mic doesn’t work after “Add to home screen“ 

### ISSUE THREAD

**Issue by TSMMark** [benawad/dogehouse#134] opened 2021-02-13 17:46 UTC
On iPhone I installed the pwa to home screen and the mic doesn’t work. Works in safari tho

![B002B77E-B934-4050-8AE9-48A3B5DECFD8](https://user-images.githubusercontent.com/4197823/107856923-7ad51000-6df9-11eb-83bb-f632a99b9ecd.png)

**Comment by PixsaOJ** [comment] 2021-02-22 20:42
Is there any option to give PWA access to microphone? Maybe you can long press PWA icon, or find the option in the settings to do that

**Comment by goldyydev** [comment] 2021-03-20 19:09
Is this still like that? Does anyone have an iPhone to reproduce this with?

**Comment by TheOtterlord** [comment] 2021-03-20 19:14
Related? https://stackoverflow.com/questions/56080829/ios-pwa-getusermedia-not-work-in-standalone-mode

**Comment by ajmnz** [comment] 2021-04-16 23:33
This issue seems to be fixed now. Mic working fine on iOS 14.4.2 and Safari.

**Closed by ajmnz** 2021-04-16 23:33 UTC
