### ISSUE TITLE
Outdated profile description

### ISSUE THREAD

**Issue by GKaszewski** [benawad/dogehouse#1613] opened 2021-03-26 19:50 UTC
**Describe the bug**
Profile description on DogeHouse doesn't match with Github account after changing it on Github.

**Expected behavior**
Updated description on my DogeHouse profile.

**Screenshots**
![image](https://user-images.githubusercontent.com/42281413/112685287-a1fd1380-8e74-11eb-9720-93324a968bb9.png)
![image](https://user-images.githubusercontent.com/42281413/112685304-a88b8b00-8e74-11eb-800a-c2a868295788.png)

**What device are you on?**
Desktop - Chrome

**Comment by goldyydev** [comment] 2021-03-26 20:35
The description isn't really supposed to update. it fetches it from github as a "courtesy".  This is intended behaviour, but may need some work.

**Comment by goldyydev** [comment] 2021-03-26 20:35
Didn't mean to close it

**Comment by samarmohan** [comment] 2021-03-27 00:09
I’m guessing you changed it because it’s your birthday, happy birthday if it is!

**Comment by GKaszewski** [comment] 2021-03-27 20:58
> The description isn't really supposed to update. it fetches it from github as a "courtesy". This is intended behaviour, but may need some work.

Yeah, I was thinking that something like that was supposed to happen. Nevertheless, it would be cool to change the description on DogeHouse.

**Comment by mkredzel** [comment] 2021-03-28 02:16
It wouldn't make much sense to make it update on every connection... what if somebody wants to customize profile description that has nothing to do with their GitHub account? 

Instead of taking it as a bug we could actually take it up as a new feature (having a button or checkbox that allows fetching the description on demand)

**Comment by MMK21Hub** [comment] 2021-03-30 15:12
By default, the bio will be taken from GitHub, but the user can uncheck the checkbox to change it.

![image](https://user-images.githubusercontent.com/50421330/113012530-c443a980-9172-11eb-9e08-b47837bc5a84.png)

**Closed as completed** 2021-04-29 13:59 UTC
Labels: bug, expected-behavior-but-awkward-and-could-get-rework
